import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "../components/footer";
import { Poppins } from "@next/font/google";

const poppins = Poppins({
  weight: ["400", "700", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SLEEPSTIQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
